[workspace]
members = [
    "chapter01/hello_cargo",
    "chapter02/guessing_game",
    "chapter03/variables",
    "chapter03/integers",
    "chapter03/floats",
    "chapter03/booleans",
    "chapter03/chars",
    "chapter03/tuples",
    ]
